### ISSUE TITLE
Publish for sbt 1.0

### ISSUE THREAD

**Issue by marconilanna** [wartremover/wartremover-contrib#18]
The final version of sbt 1.0 is already released.

**Comment by NeQuissimus** [comment]
@ClaireNeveu Maybe you could apply your SBT 1.0 magic to the contrib build as well? :D

**Comment by omervk** [comment]
I tried taking a stab at this, but I couldn't figure it out in a decent amount of time. 😞 

Hope someone else can pick this up soon.

**Comment by ClaireNeveu** [comment]
See https://github.com/wartremover/wartremover/pull/400 for reference.

**Comment by danielnixon** [comment]
https://github.com/wartremover/wartremover-contrib/pull/21 should do it.

**Comment by omervk** [comment]
Thanks, @danielnixon! Would it be possible for you or @ClaireNeveu to release 1.1.0?

**Comment by ClaireNeveu** [comment]
I'm away from my computer for the week but I can cut a release next weekend.

**Comment by TkDodo** [comment]
Release 1.1.0 with PR #21 would be greatly appreciated. Thanks and keep up the good work

**Comment by omervk** [comment]
@ClaireNeveu I'd love to have my team move to 1.0.x and this is the only plugin left that hasn't made the move. Is there any way in which I can help?

**Comment by ClaireNeveu** [comment]
1.1.0 is out.

**Comment by omervk** [comment]
Thank you :)
