### ISSUE TITLE
NoNeedForMonadTest tests a wrong class

### ISSUE THREAD

**Issue by amanjpro** [wartremover/wartremover-contrib#2]
The `NoNeedForMonadTest` tests `org.wartremover.warts.NoNeedForMonad` not the wart provided by this contrib package (aka: `org.wartremover.warts.contrib.NoNeedForMonad`)

For more, please see this:

https://github.com/wartremover/wartremover-contrib/blob/master/src/test/scala/wartremover/contrib/warts/NoNeedForMonadTest.scala#L7

**Comment by ChrisNeveu** [comment]
Thanks for the catch!

**Comment by amanjpro** [comment]
It is not only a typo, the test cases also fail if you change it to contrib's NoNeedForMonad.

Because of this change, my pull request does not pass the test.

https://github.com/wartremover/wartremover-contrib/commit/c0bae11418cf5d8a761c30014287c052f9c0dad0

**Comment by amanjpro** [comment]
@ChrisNeveu
