### ISSUE TITLE
Add a maven/ivy artifact for this project

### ISSUE THREAD

**Issue by amanjpro** [wartremover/wartremover-contrib#4]
It would be really helpful to have a maven/ivy artifact for this project.

**Comment by amanjpro** [comment]
I am not really sure how can we manage the dependency between this and the mother project. This depends on the wartremover project (easy).

But what is really hard is to pass this as the dependency to the wartremover _compiler_ plugin. Anybody has an idea?

**Comment by ChrisNeveu** [comment]
@amanjpro I'm going to set up the sbt plugin for contrib today.

**Comment by amanjpro** [comment]
Thank you very much

**Comment by ChrisNeveu** [comment]
The 1.0.0 release is out now.

**Comment by amanjpro** [comment]
Does this also serve users of other build tools, like Maven and so?

**Comment by ChrisNeveu** [comment]
See the "Other Ways" section of http://wartremover.github.io/wartremover/doc/install-setup.html.

**Comment by amanjpro** [comment]
I wasn't sure if it works for this. Will try it now

**Comment by amanjpro** [comment]
Actually it does not work. Here is my setup:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>net.alchim31.maven</groupId>
      <artifactId>scala-maven-plugin</artifactId>
      <version>3.2.1</version>
      <configuration>
        <compilerPlugins>
          <compilerPlugin>
            <groupId>org.wartremover</groupId>
            <artifactId>wartremover-contrib_2.12</artifactId>
            <version>1.0.0</version>
          </compilerPlugin>
        </compilerPlugins>
        <args>
          <arg>-P:wartremover:only-warn-traverser:org.wartremover.contrib.warts.SomeApply</arg>
        </args>
      </configuration>
    </plugin>
  </plugins>
</build>
```

And I get the following error while trying to compile my project:

```shell
[WARNING] Warning: could not load descriptor for plugin /Users/amanj/.m2/repository/org/wartremover/wartremover-contrib_2.12/1.0.0/wartremover-contrib_2.12-1.0.0.jar
[ERROR] error: bad option: -P:wartremover:only-warn-traverser:org.wartremover.contrib.warts.SomeApply
```

**Comment by ChrisNeveu** [comment]
I don't use Maven so I don't know what the correct way to do this is but it looks like you're not adding wartremover-contrib's classpath to `wartremoverClasspaths`.

**Comment by amanjpro** [comment]
Ah, so I also need to use wartremover. I thought this is self-contained

**Comment by amanjpro** [comment]
It turned out that using this with maven was not straightforward, I spent a few hours to crack it! I have added it to the repo (other_ways.md)
