### ISSUE TITLE
Release for Scala 2.13.13

### ISSUE THREAD

**Issue by mvestola** [wartremover/wartremover-contrib#479]
Latest 2.1.0 does not seem to work with Scala 2.13.13, so should probably create new release? Getting this error:
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.wartremover:wartremover-contrib_2.13.13:2.1.0
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.wartremover/wartremover-contrib_2.13.13/2.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/wartremover/wartremover-contrib_2.13.13/2.1.0/wartremover-contrib_2.13.13-2.1.0.pom
```
This release seems to be missing:
https://repo1.maven.org/maven2/org/wartremover/wartremover-contrib_2.13.13/2.1.0/wartremover-contrib_2.13.13-2.1.0.pom

Works with Scala 2.13.12:
https://repo1.maven.org/maven2/org/wartremover/wartremover-contrib_2.13.12/2.1.0/wartremover-contrib_2.13.12-2.1.0.pom

2.13.13 not listed here either:
https://mvnrepository.com/artifact/org.wartremover/wartremover-contrib

Used this:
```
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.1.6")
addSbtPlugin("org.wartremover" % "sbt-wartremover-contrib" % "2.1.0")
```

**Comment by rgugliel-da** [comment]
Any news on this ?
