### ISSUE TITLE
Publish for Scala 2.12.11 and wartremover 2.4.5

### ISSUE THREAD

**Issue by marconilanna** [wartremover/wartremover-contrib#49]
Could you please publish for Scala 2.12.11 and wartremover 2.4.5? Right now, if you try to use this plugin with Scala 2.12.11 and wartremover 2.4.5, you get the following error:

```
Error downloading org.wartremover:wartremover_2.12.11:2.4.4
not found: https://repo1.maven.org/maven2/org/wartremover/wartremover_2.12.11/2.4.4/wartremover_2.12.11-2.4.4.pom
not found: https://dl.bintray.com/jmcardon/tsec/org/wartremover/wartremover_2.12.11/2.4.4/wartremover_2.12.11-2.4.4.pom
```

Notice the 2.4.4 version

**Comment by exoego** [comment]
@xuwei-k Could you publish wartremover-contrib against wartremover 2.4.5, since wartremover 2.4.5 had been published for Scala 2.12.11.
https://github.com/wartremover/wartremover/issues/470

**Comment by xuwei-k** [comment]
wartremover-contrib does not use `CrossVersion.full`. 
if publish new wartremover-contrib with `"wartremover_2.12.11" % "2.4.5"` I think it cause same error for Scala 2.12.x (x <= 10).

I think wartrmover 2.4.4 to 2.4.5 backward binary compatible.

https://github.com/wartremover/wartremover/compare/v2.4.4...v2.4.5

please add

```scala
dependencyOverrides += "org.wartremover" %% "wartremover" % "2.4.5" cross CrossVersion.full
```

in your build.sbt.

**Comment by exoego** [comment]
Unfortunately, none of below codes work... 🤔 

```scala
val wartremoverVersion = "2.4.5"
addSbtPlugin("org.wartremover" % "sbt-wartremover" % wartremoverVersion)
addSbtPlugin("org.wartremover" % "sbt-wartremover-contrib" % "1.3.4")
dependencyOverrides += "org.wartremover" %% "wartremover" % wartremoverVersion cross CrossVersion.full
```

```scala
val wartremoverVersion = "2.4.5"
addSbtPlugin("org.wartremover" % "sbt-wartremover-contrib" % "1.3.4")
dependencyOverrides += "org.wartremover" %% "wartremover" % wartremoverVersion cross CrossVersion.full
```

**Comment by xuwei-k** [comment]
not `project/plugins.sbt`. `build.sbt`

**Comment by xuwei-k** [comment]
- https://github.com/wartremover/wartremover-contrib/commit/297545ea43f209cf2a299f278e8370ea1e9bd7e0
- https://github.com/wartremover/wartremover/commit/7afa7ebaece20475a4de10f208a75a470404ddeb

**Comment by exoego** [comment]
@xuwei-k Thanks for quick fix and publishing 👍 
The below in `project/plugins.sbt` works wih Scala 2.12.11 for me.
```scala
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.5")
addSbtPlugin("org.wartremover" % "sbt-wartremover-contrib" % "1.3.5")
```
